package com.obins.anne.utils;

import android.support.v4.media.TransportMediator;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class KeyObjectUtil {
    public static List<KeyObject> baseKeyObjectList = new ArrayList();
    public static List<KeyObject> bigKeyObjectList = new ArrayList();
    public static List<KeyObject> emptyObjectList = new ArrayList();
    public static List<KeyObject> fareaKeyObjectList = new ArrayList();
    public static List<KeyObject> funKeyObjectList = new ArrayList();
    public static KeyObject keyObject0 = new KeyObject();
    public static KeyObject keyObject1 = new KeyObject();
    public static KeyObject keyObject2 = new KeyObject();
    public static KeyObject keyObject3 = new KeyObject();
    public static KeyObject keyObject4 = new KeyObject();
    public static KeyObject keyObject5 = new KeyObject();
    public static KeyObject keyObject6 = new KeyObject();
    public static KeyObject keyObject7 = new KeyObject();
    public static KeyObject keyObject8 = new KeyObject();
    public static KeyObject keyObject9 = new KeyObject();
    public static KeyObject keyObjectA = new KeyObject();
    public static KeyObject keyObjectANNE = new KeyObject();
    public static KeyObject keyObjectAgain = new KeyObject();
    public static KeyObject keyObjectB = new KeyObject();
    public static KeyObject keyObjectBackspace = new KeyObject();
    public static KeyObject keyObjectBigThan = new KeyObject();
    public static KeyObject keyObjectC = new KeyObject();
    public static KeyObject keyObjectCAPS = new KeyObject();
    public static KeyObject keyObjectColon = new KeyObject();
    public static KeyObject keyObjectCopy = new KeyObject();
    public static KeyObject keyObjectCut = new KeyObject();
    public static KeyObject keyObjectD = new KeyObject();
    public static KeyObject keyObjectDelete = new KeyObject();
    public static KeyObject keyObjectDown = new KeyObject();
    public static KeyObject keyObjectE = new KeyObject();
    public static KeyObject keyObjectENTER = new KeyObject();
    public static KeyObject keyObjectESC = new KeyObject();
    public static KeyObject keyObjectEnd = new KeyObject();
    public static KeyObject keyObjectExecute = new KeyObject();
    public static KeyObject keyObjectF = new KeyObject();
    public static KeyObject keyObjectF1 = new KeyObject();
    public static KeyObject keyObjectF10 = new KeyObject();
    public static KeyObject keyObjectF11 = new KeyObject();
    public static KeyObject keyObjectF12 = new KeyObject();
    public static KeyObject keyObjectF2 = new KeyObject();
    public static KeyObject keyObjectF3 = new KeyObject();
    public static KeyObject keyObjectF4 = new KeyObject();
    public static KeyObject keyObjectF5 = new KeyObject();
    public static KeyObject keyObjectF6 = new KeyObject();
    public static KeyObject keyObjectF7 = new KeyObject();
    public static KeyObject keyObjectF8 = new KeyObject();
    public static KeyObject keyObjectF9 = new KeyObject();
    public static KeyObject keyObjectFN = new KeyObject();
    public static KeyObject keyObjectFind = new KeyObject();
    public static KeyObject keyObjectG = new KeyObject();
    public static KeyObject keyObjectH = new KeyObject();
    public static KeyObject keyObjectHelp = new KeyObject();
    public static KeyObject keyObjectHome = new KeyObject();
    public static KeyObject keyObjectI = new KeyObject();
    public static KeyObject keyObjectInsert = new KeyObject();
    public static KeyObject keyObjectJ = new KeyObject();
    public static KeyObject keyObjectK = new KeyObject();
    public static KeyObject keyObjectL = new KeyObject();
    public static KeyObject keyObjectLALT = new KeyObject();
    public static KeyObject keyObjectLBrackets = new KeyObject();
    public static KeyObject keyObjectLCTRL = new KeyObject();
    public static KeyObject keyObjectLCmd = new KeyObject();
    public static KeyObject keyObjectLOption = new KeyObject();
    public static KeyObject keyObjectLSHIFT = new KeyObject();
    public static KeyObject keyObjectLWin = new KeyObject();
    public static KeyObject keyObjectLeft = new KeyObject();
    public static KeyObject keyObjectLessThan = new KeyObject();
    public static KeyObject keyObjectM = new KeyObject();
    public static KeyObject keyObjectMenu = new KeyObject();
    public static KeyObject keyObjectMinus = new KeyObject();
    public static KeyObject keyObjectMute = new KeyObject();
    public static KeyObject keyObjectN = new KeyObject();
    public static KeyObject keyObjectO = new KeyObject();
    public static KeyObject keyObjectP = new KeyObject();
    public static KeyObject keyObjectPageDown = new KeyObject();
    public static KeyObject keyObjectPageUp = new KeyObject();
    public static KeyObject keyObjectPaste = new KeyObject();
    public static KeyObject keyObjectPause = new KeyObject();
    public static KeyObject keyObjectPlus = new KeyObject();
    public static KeyObject keyObjectPrintScreen = new KeyObject();
    public static KeyObject keyObjectQ = new KeyObject();
    public static KeyObject keyObjectQuestion = new KeyObject();
    public static KeyObject keyObjectQuotes = new KeyObject();
    public static KeyObject keyObjectR = new KeyObject();
    public static KeyObject keyObjectRALT = new KeyObject();
    public static KeyObject keyObjectRBrackets = new KeyObject();
    public static KeyObject keyObjectRCTRL = new KeyObject();
    public static KeyObject keyObjectRCmd = new KeyObject();
    public static KeyObject keyObjectROption = new KeyObject();
    public static KeyObject keyObjectRSHIFT = new KeyObject();
    public static KeyObject keyObjectRWin = new KeyObject();
    public static KeyObject keyObjectReserved = new KeyObject();
    public static KeyObject keyObjectRight = new KeyObject();
    public static KeyObject keyObjectS = new KeyObject();
    public static KeyObject keyObjectSPACE = new KeyObject();
    public static KeyObject keyObjectScrollLock = new KeyObject();
    public static KeyObject keyObjectSelect = new KeyObject();
    public static KeyObject keyObjectStop = new KeyObject();
    public static KeyObject keyObjectT = new KeyObject();
    public static KeyObject keyObjectTAB = new KeyObject();
    public static KeyObject keyObjectTilde = new KeyObject();
    public static KeyObject keyObjectU = new KeyObject();
    public static KeyObject keyObjectUndo = new KeyObject();
    public static KeyObject keyObjectUp = new KeyObject();
    public static KeyObject keyObjectV = new KeyObject();
    public static KeyObject keyObjectVertical = new KeyObject();
    public static KeyObject keyObjectVolumeDown = new KeyObject();
    public static KeyObject keyObjectVolumeUp = new KeyObject();
    public static KeyObject keyObjectW = new KeyObject();
    public static KeyObject keyObjectWinLock = new KeyObject();
    public static KeyObject keyObjectX = new KeyObject();
    public static KeyObject keyObjectY = new KeyObject();
    public static KeyObject keyObjectZ = new KeyObject();
    public static final HashMap<Integer, String> keyValueAndStringMap = new HashMap();
    public static List<KeyObject> macroBigKeyObjectList = new ArrayList();
    public static List<KeyObject> mediaKeyObjectList = new ArrayList();
    public static List<KeyObject> numKeyObjectList = new ArrayList();
    public static List<KeyObject> symbolKeyObjectList = new ArrayList();
    public static List<KeyObject> systemKeyAndEmptyObjectList = new ArrayList();
    public static List<KeyObject> systemKeyObjectList = new ArrayList();

    static {
        int i;
        keyObjectReserved.keyStr = AppConfig.SERVER_IP;
        keyObjectReserved.keyValue = 0;
        keyObjectANNE.keyStr = "anne";
        keyObjectANNE.keyStrComplete = "ANNE";
        keyObjectANNE.keyValue = 250;
        keyObjectFN.keyStr = "fn";
        keyObjectFN.keyStrComplete = "FN";
        keyObjectFN.keyValue = 254;
        keyObjectWinLock.keyStr = "lock";
        keyObjectWinLock.keyStrComplete = "Win_Lock";
        keyObjectWinLock.keyValue = 227;
        keyObjectA.keyStr = "A";
        keyObjectB.keyStr = "B";
        keyObjectC.keyStr = "C";
        keyObjectD.keyStr = "D";
        keyObjectE.keyStr = "E";
        keyObjectF.keyStr = "F";
        keyObjectG.keyStr = "G";
        keyObjectH.keyStr = "H";
        keyObjectI.keyStr = "I";
        keyObjectJ.keyStr = "J";
        keyObjectK.keyStr = "K";
        keyObjectL.keyStr = "L";
        keyObjectN.keyStr = "N";
        keyObjectM.keyStr = "M";
        keyObjectO.keyStr = "O";
        keyObjectP.keyStr = "P";
        keyObjectQ.keyStr = "Q";
        keyObjectR.keyStr = "R";
        keyObjectS.keyStr = "S";
        keyObjectT.keyStr = "T";
        keyObjectU.keyStr = "U";
        keyObjectV.keyStr = "V";
        keyObjectW.keyStr = "W";
        keyObjectX.keyStr = "X";
        keyObjectY.keyStr = "Y";
        keyObjectZ.keyStr = "Z";
        keyObjectA.keyValue = 4;
        keyObjectB.keyValue = 5;
        keyObjectC.keyValue = 6;
        keyObjectD.keyValue = 7;
        keyObjectE.keyValue = 8;
        keyObjectF.keyValue = 9;
        keyObjectG.keyValue = 10;
        keyObjectH.keyValue = 11;
        keyObjectI.keyValue = 12;
        keyObjectJ.keyValue = 13;
        keyObjectK.keyValue = 14;
        keyObjectL.keyValue = 15;
        keyObjectN.keyValue = 17;
        keyObjectM.keyValue = 16;
        keyObjectO.keyValue = 18;
        keyObjectP.keyValue = 19;
        keyObjectQ.keyValue = 20;
        keyObjectR.keyValue = 21;
        keyObjectS.keyValue = 22;
        keyObjectT.keyValue = 23;
        keyObjectU.keyValue = 24;
        keyObjectV.keyValue = 25;
        keyObjectW.keyValue = 26;
        keyObjectX.keyValue = 27;
        keyObjectY.keyValue = 28;
        keyObjectZ.keyValue = 29;
        keyObject0.keyStr = "0";
        keyObject1.keyStr = "1";
        keyObject2.keyStr = "2";
        keyObject3.keyStr = "3";
        keyObject4.keyStr = "4";
        keyObject5.keyStr = "5";
        keyObject6.keyStr = "6";
        keyObject7.keyStr = "7";
        keyObject8.keyStr = "8";
        keyObject9.keyStr = "9";
        keyObject0.keyValue = 39;
        keyObject1.keyValue = 30;
        keyObject2.keyValue = 31;
        keyObject3.keyValue = 32;
        keyObject4.keyValue = 33;
        keyObject5.keyValue = 34;
        keyObject6.keyValue = 35;
        keyObject7.keyValue = 36;
        keyObject8.keyValue = 37;
        keyObject9.keyValue = 38;
        keyObjectESC.keyStr = "esc";
        keyObjectTAB.keyStr = "tab";
        keyObjectCAPS.keyStr = "caps";
        keyObjectLSHIFT.keyStr = "shift";
        keyObjectLCTRL.keyStr = "ctrl";
        keyObjectLALT.keyStr = "alt";
        keyObjectSPACE.keyStr = "space";
        keyObjectRCTRL.keyStr = "ctrl";
        keyObjectRALT.keyStr = "alt";
        keyObjectRSHIFT.keyStr = "shift";
        keyObjectENTER.keyStr = "enter";
        keyObjectBackspace.keyStr = "bkspace";
        keyObjectLWin.keyStr = "win";
        keyObjectRWin.keyStr = "win";
        keyObjectLCmd.keyStr = "cmd";
        keyObjectRCmd.keyStr = "cmd";
        keyObjectLOption.keyStr = "opt";
        keyObjectROption.keyStr = "opt";
        keyObjectESC.keyStrComplete = "ESC";
        keyObjectTAB.keyStrComplete = "TAB";
        keyObjectCAPS.keyStrComplete = "CAPS";
        keyObjectLSHIFT.keyStrComplete = "L_SHIFT";
        keyObjectLCTRL.keyStrComplete = "L_CTRL";
        keyObjectLALT.keyStrComplete = "L_ALT";
        keyObjectSPACE.keyStrComplete = "SPACE";
        keyObjectRCTRL.keyStrComplete = "R_CTRL";
        keyObjectRALT.keyStrComplete = "R_ALT";
        keyObjectRSHIFT.keyStrComplete = "R_SHIFT";
        keyObjectENTER.keyStrComplete = "ENTER";
        keyObjectBackspace.keyStrComplete = "Bkspace";
        keyObjectLWin.keyStrComplete = "L_WIN";
        keyObjectRWin.keyStrComplete = "R_WIN";
        keyObjectLCmd.keyStrComplete = "L_CMD";
        keyObjectRCmd.keyStrComplete = "R_CMD";
        keyObjectLOption.keyStrComplete = "L_Option";
        keyObjectROption.keyStrComplete = "R_Option";
        keyObjectESC.keyValue = 41;
        keyObjectTAB.keyValue = 43;
        keyObjectCAPS.keyValue = 57;
        keyObjectLSHIFT.keyValue = 225;
        keyObjectLCTRL.keyValue = 224;
        keyObjectLALT.keyValue = 226;
        keyObjectSPACE.keyValue = 44;
        keyObjectRCTRL.keyValue = 228;
        keyObjectRALT.keyValue = 230;
        keyObjectRSHIFT.keyValue = 229;
        keyObjectENTER.keyValue = 40;
        keyObjectBackspace.keyValue = 42;
        keyObjectLWin.keyValue = 227;
        keyObjectRWin.keyValue = 231;
        keyObjectLCmd.keyValue = 227;
        keyObjectRCmd.keyValue = 231;
        keyObjectLOption.keyValue = 226;
        keyObjectROption.keyValue = 230;
        keyObjectTilde.keyStr = "`~";
        keyObjectVertical.keyStr = "\\|";
        keyObjectMinus.keyStr = "-_";
        keyObjectPlus.keyStr = "=+";
        keyObjectLBrackets.keyStr = "[{";
        keyObjectRBrackets.keyStr = "]}";
        keyObjectColon.keyStr = ";:";
        keyObjectQuotes.keyStr = "\"";
        keyObjectLessThan.keyStr = ",<";
        keyObjectBigThan.keyStr = ".>";
        keyObjectQuestion.keyStr = "/?";
        keyObjectTilde.keyValue = 53;
        keyObjectVertical.keyValue = 49;
        keyObjectMinus.keyValue = 45;
        keyObjectPlus.keyValue = 46;
        keyObjectLBrackets.keyValue = 47;
        keyObjectRBrackets.keyValue = 48;
        keyObjectColon.keyValue = 51;
        keyObjectQuotes.keyValue = 52;
        keyObjectLessThan.keyValue = 54;
        keyObjectBigThan.keyValue = 55;
        keyObjectQuestion.keyValue = 56;
        keyObjectF1.keyStr = "F1";
        keyObjectF2.keyStr = "F2";
        keyObjectF3.keyStr = "F3";
        keyObjectF4.keyStr = "F4";
        keyObjectF5.keyStr = "F5";
        keyObjectF6.keyStr = "F6";
        keyObjectF7.keyStr = "F7";
        keyObjectF8.keyStr = "F8";
        keyObjectF9.keyStr = "F9";
        keyObjectF10.keyStr = "F10";
        keyObjectF11.keyStr = "F11";
        keyObjectF12.keyStr = "F12";
        keyObjectF1.keyValue = 58;
        keyObjectF2.keyValue = 59;
        keyObjectF3.keyValue = 60;
        keyObjectF4.keyValue = 61;
        keyObjectF5.keyValue = 62;
        keyObjectF6.keyValue = 63;
        keyObjectF7.keyValue = 64;
        keyObjectF8.keyValue = 65;
        keyObjectF9.keyValue = 66;
        keyObjectF10.keyValue = 67;
        keyObjectF11.keyValue = 68;
        keyObjectF12.keyValue = 69;
        keyObjectUp.keyStr = "up";
        keyObjectDown.keyStr = "dn";
        keyObjectLeft.keyStr = "lt";
        keyObjectRight.keyStr = "rt";
        keyObjectUp.keyStrComplete = "Up";
        keyObjectDown.keyStrComplete = "Down";
        keyObjectLeft.keyStrComplete = "Left";
        keyObjectRight.keyStrComplete = "Right";
        keyObjectUp.keyValue = 82;
        keyObjectDown.keyValue = 81;
        keyObjectLeft.keyValue = 80;
        keyObjectRight.keyValue = 79;
        keyObjectPrintScreen.keyStr = "ps";
        keyObjectScrollLock.keyStr = "sc";
        keyObjectPause.keyStr = "pb";
        keyObjectInsert.keyStr = "ins";
        keyObjectDelete.keyStr = "del";
        keyObjectHome.keyStr = "hm";
        keyObjectEnd.keyStr = "end";
        keyObjectPageUp.keyStr = "pu";
        keyObjectPageDown.keyStr = "pd";
        keyObjectPrintScreen.keyStrComplete = "Prt Sc";
        keyObjectScrollLock.keyStrComplete = "Scr Lk";
        keyObjectPause.keyStrComplete = "Pause";
        keyObjectInsert.keyStrComplete = "Insert";
        keyObjectDelete.keyStrComplete = "Delete";
        keyObjectHome.keyStrComplete = "Home";
        keyObjectEnd.keyStrComplete = "End";
        keyObjectPageUp.keyStrComplete = "PageUp";
        keyObjectPageDown.keyStrComplete = "PageDown";
        keyObjectPrintScreen.keyValue = 70;
        keyObjectScrollLock.keyValue = 71;
        keyObjectPause.keyValue = 72;
        keyObjectInsert.keyValue = 73;
        keyObjectDelete.keyValue = 76;
        keyObjectHome.keyValue = 74;
        keyObjectEnd.keyValue = 77;
        keyObjectPageUp.keyValue = 75;
        keyObjectPageDown.keyValue = 78;
        keyObjectMute.keyStr = "mt";
        keyObjectVolumeUp.keyStr = "vp";
        keyObjectVolumeDown.keyStr = "vd";
        keyObjectMute.keyStrComplete = "Mute";
        keyObjectVolumeUp.keyStrComplete = "Vol Up";
        keyObjectVolumeDown.keyStrComplete = "Vol Down";
        keyObjectMute.keyValue = TransportMediator.KEYCODE_MEDIA_PAUSE;
        keyObjectVolumeUp.keyValue = 128;
        keyObjectVolumeDown.keyValue = 129;
        keyObjectExecute.keyValue = 116;
        keyObjectHelp.keyValue = 117;
        keyObjectMenu.keyValue = 118;
        keyObjectSelect.keyValue = 119;
        keyObjectStop.keyValue = 120;
        keyObjectAgain.keyValue = 121;
        keyObjectUndo.keyValue = 122;
        keyObjectCut.keyValue = 123;
        keyObjectCopy.keyValue = 124;
        keyObjectPaste.keyValue = 125;
        keyObjectFind.keyValue = TransportMediator.KEYCODE_MEDIA_PLAY;
        keyObjectExecute.keyStr = "py";
        keyObjectHelp.keyStr = "hp";
        keyObjectMenu.keyStr = "mu";
        keyObjectSelect.keyStr = "slt";
        keyObjectStop.keyStr = "stp";
        keyObjectAgain.keyStr = "aga";
        keyObjectUndo.keyStr = "udo";
        keyObjectCut.keyStr = "cut";
        keyObjectCopy.keyStr = "cpy";
        keyObjectPaste.keyStr = "pst";
        keyObjectFind.keyStr = "fnd";
        keyObjectExecute.keyStrComplete = "Play";
        keyObjectHelp.keyStrComplete = "Help";
        keyObjectMenu.keyStrComplete = "Menu";
        keyObjectSelect.keyStrComplete = "Select";
        keyObjectStop.keyStrComplete = "Stop";
        keyObjectAgain.keyStrComplete = "Again";
        keyObjectUndo.keyStrComplete = "Undo";
        keyObjectCut.keyStrComplete = "Cut";
        keyObjectCopy.keyStrComplete = "Copy";
        keyObjectPaste.keyStrComplete = "Paste";
        keyObjectFind.keyStrComplete = "Find";
        systemKeyObjectList.add(keyObjectFN);
        systemKeyObjectList.add(keyObjectANNE);
        systemKeyAndEmptyObjectList.add(keyObjectFN);
        systemKeyAndEmptyObjectList.add(keyObjectANNE);
        systemKeyAndEmptyObjectList.add(keyObjectReserved);
        emptyObjectList.add(keyObjectReserved);
        baseKeyObjectList.add(keyObjectA);
        baseKeyObjectList.add(keyObjectB);
        baseKeyObjectList.add(keyObjectC);
        baseKeyObjectList.add(keyObjectD);
        baseKeyObjectList.add(keyObjectE);
        baseKeyObjectList.add(keyObjectF);
        baseKeyObjectList.add(keyObjectG);
        baseKeyObjectList.add(keyObjectH);
        baseKeyObjectList.add(keyObjectI);
        baseKeyObjectList.add(keyObjectJ);
        baseKeyObjectList.add(keyObjectK);
        baseKeyObjectList.add(keyObjectL);
        baseKeyObjectList.add(keyObjectM);
        baseKeyObjectList.add(keyObjectN);
        baseKeyObjectList.add(keyObjectO);
        baseKeyObjectList.add(keyObjectP);
        baseKeyObjectList.add(keyObjectQ);
        baseKeyObjectList.add(keyObjectR);
        baseKeyObjectList.add(keyObjectS);
        baseKeyObjectList.add(keyObjectT);
        baseKeyObjectList.add(keyObjectU);
        baseKeyObjectList.add(keyObjectV);
        baseKeyObjectList.add(keyObjectW);
        baseKeyObjectList.add(keyObjectX);
        baseKeyObjectList.add(keyObjectY);
        baseKeyObjectList.add(keyObjectZ);
        numKeyObjectList.add(keyObject0);
        numKeyObjectList.add(keyObject1);
        numKeyObjectList.add(keyObject2);
        numKeyObjectList.add(keyObject3);
        numKeyObjectList.add(keyObject4);
        numKeyObjectList.add(keyObject5);
        numKeyObjectList.add(keyObject6);
        numKeyObjectList.add(keyObject7);
        numKeyObjectList.add(keyObject8);
        numKeyObjectList.add(keyObject9);
        bigKeyObjectList.add(keyObjectESC);
        bigKeyObjectList.add(keyObjectTAB);
        bigKeyObjectList.add(keyObjectCAPS);
        bigKeyObjectList.add(keyObjectLSHIFT);
        bigKeyObjectList.add(keyObjectLCTRL);
        bigKeyObjectList.add(keyObjectLWin);
        bigKeyObjectList.add(keyObjectRWin);
        bigKeyObjectList.add(keyObjectLCmd);
        bigKeyObjectList.add(keyObjectRCmd);
        bigKeyObjectList.add(keyObjectLOption);
        bigKeyObjectList.add(keyObjectROption);
        bigKeyObjectList.add(keyObjectLALT);
        bigKeyObjectList.add(keyObjectSPACE);
        bigKeyObjectList.add(keyObjectRALT);
        bigKeyObjectList.add(keyObjectRCTRL);
        bigKeyObjectList.add(keyObjectRSHIFT);
        bigKeyObjectList.add(keyObjectENTER);
        bigKeyObjectList.add(keyObjectBackspace);
        macroBigKeyObjectList.add(keyObjectESC);
        macroBigKeyObjectList.add(keyObjectTAB);
        macroBigKeyObjectList.add(keyObjectCAPS);
        macroBigKeyObjectList.add(keyObjectLSHIFT);
        macroBigKeyObjectList.add(keyObjectLCTRL);
        macroBigKeyObjectList.add(keyObjectLWin);
        macroBigKeyObjectList.add(keyObjectLALT);
        macroBigKeyObjectList.add(keyObjectSPACE);
        macroBigKeyObjectList.add(keyObjectRALT);
        macroBigKeyObjectList.add(keyObjectRCTRL);
        macroBigKeyObjectList.add(keyObjectRSHIFT);
        macroBigKeyObjectList.add(keyObjectENTER);
        macroBigKeyObjectList.add(keyObjectBackspace);
        symbolKeyObjectList.add(keyObjectTilde);
        symbolKeyObjectList.add(keyObjectMinus);
        symbolKeyObjectList.add(keyObjectPlus);
        symbolKeyObjectList.add(keyObjectLBrackets);
        symbolKeyObjectList.add(keyObjectRBrackets);
        symbolKeyObjectList.add(keyObjectVertical);
        symbolKeyObjectList.add(keyObjectColon);
        symbolKeyObjectList.add(keyObjectQuotes);
        symbolKeyObjectList.add(keyObjectLessThan);
        symbolKeyObjectList.add(keyObjectBigThan);
        symbolKeyObjectList.add(keyObjectQuestion);
        fareaKeyObjectList.add(keyObjectF1);
        fareaKeyObjectList.add(keyObjectF2);
        fareaKeyObjectList.add(keyObjectF3);
        fareaKeyObjectList.add(keyObjectF4);
        fareaKeyObjectList.add(keyObjectF5);
        fareaKeyObjectList.add(keyObjectF6);
        fareaKeyObjectList.add(keyObjectF7);
        fareaKeyObjectList.add(keyObjectF8);
        fareaKeyObjectList.add(keyObjectF9);
        fareaKeyObjectList.add(keyObjectF10);
        fareaKeyObjectList.add(keyObjectF11);
        fareaKeyObjectList.add(keyObjectF12);
        funKeyObjectList.add(keyObjectPrintScreen);
        funKeyObjectList.add(keyObjectScrollLock);
        funKeyObjectList.add(keyObjectPause);
        funKeyObjectList.add(keyObjectInsert);
        funKeyObjectList.add(keyObjectDelete);
        funKeyObjectList.add(keyObjectHome);
        funKeyObjectList.add(keyObjectEnd);
        funKeyObjectList.add(keyObjectPageDown);
        funKeyObjectList.add(keyObjectPageUp);
        funKeyObjectList.add(keyObjectLeft);
        funKeyObjectList.add(keyObjectUp);
        funKeyObjectList.add(keyObjectDown);
        funKeyObjectList.add(keyObjectRight);
        mediaKeyObjectList.add(keyObjectMute);
        mediaKeyObjectList.add(keyObjectVolumeUp);
        mediaKeyObjectList.add(keyObjectVolumeDown);
        for (i = 0; i < systemKeyObjectList.size(); i++) {
            keyValueAndStringMap.put(Integer.valueOf(((KeyObject) systemKeyObjectList.get(i)).keyValue), ((KeyObject) systemKeyObjectList.get(i)).keyStr);
        }
        for (i = 0; i < baseKeyObjectList.size(); i++) {
            keyValueAndStringMap.put(Integer.valueOf(((KeyObject) baseKeyObjectList.get(i)).keyValue), ((KeyObject) baseKeyObjectList.get(i)).keyStr);
        }
        for (i = 0; i < bigKeyObjectList.size(); i++) {
            keyValueAndStringMap.put(Integer.valueOf(((KeyObject) bigKeyObjectList.get(i)).keyValue), ((KeyObject) bigKeyObjectList.get(i)).keyStr);
        }
        for (i = 0; i < symbolKeyObjectList.size(); i++) {
            keyValueAndStringMap.put(Integer.valueOf(((KeyObject) symbolKeyObjectList.get(i)).keyValue), ((KeyObject) symbolKeyObjectList.get(i)).keyStr);
        }
        for (i = 0; i < fareaKeyObjectList.size(); i++) {
            keyValueAndStringMap.put(Integer.valueOf(((KeyObject) fareaKeyObjectList.get(i)).keyValue), ((KeyObject) fareaKeyObjectList.get(i)).keyStr);
        }
        for (i = 0; i < funKeyObjectList.size(); i++) {
            keyValueAndStringMap.put(Integer.valueOf(((KeyObject) funKeyObjectList.get(i)).keyValue), ((KeyObject) funKeyObjectList.get(i)).keyStr);
        }
        for (i = 0; i < mediaKeyObjectList.size(); i++) {
            keyValueAndStringMap.put(Integer.valueOf(((KeyObject) mediaKeyObjectList.get(i)).keyValue), ((KeyObject) mediaKeyObjectList.get(i)).keyStr);
        }
        for (i = 0; i < numKeyObjectList.size(); i++) {
            keyValueAndStringMap.put(Integer.valueOf(((KeyObject) numKeyObjectList.get(i)).keyValue), ((KeyObject) numKeyObjectList.get(i)).keyStr);
        }
    }
}
